/*
 * jPOS Presentation Manager [http://jpospm.blogspot.com]
 * Copyright (C) 2010 Jeronimo Paoletti [jeronimo.paoletti@gmail.com]
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.jpos.ee.pm.core.monitor;

/**This class is executed by PM for each line generated by the monitor. This must return
 * an HTML formatted String to output. <br/>
 * By default, the formatter returns the line "as is". 
 * Programmer can extend this class and redefine format method to change the output.
 * */
public class MonitorFormatter {
	/**Called for each line generated by the monitor before output it on the result HTML. 
	 * @param line Monitor line
	 * @return Formatted monitor line*/
	public String format(String line){
		return line;
	}
}
