package org.jpos.ee.pm.core.monitor;

/**This class is executed by PM for each line generated by the monitor. This must return
 * an HTML formatted String to output. <br/>
 * By default, the formatter returns the line "as is". 
 * Programmer can extend this class and redefine format method to change the output.
 * */
public class MonitorFormatter {
	/**Called for each line generated by the monitor before output it on the result HTML. 
	 * @param line Monitor line
	 * @return Formatted monitor line*/
	public String format(String line){
		return line;
	}
}
